### ISSUE TITLE
Multiple zero values retrieved throughout the day for delivery/production of Zonneplan home battery

### ISSUE THREAD

**Issue by marcelswinkels** [fsaris/home-assistant-zonneplan-one#102]
Since March 20th, I see that multiple times during the day, a 0 value is returned for the home battery's delivery and production. Because of that, it looks like Home Assistant is adding up the next correct value to the daily amount in the energy monitor.

![image](https://github.com/fsaris/home-assistant-zonneplan-one/assets/55435907/baf3ce00-7121-4fc8-907b-954f785697e0)

![image](https://github.com/fsaris/home-assistant-zonneplan-one/assets/55435907/ed85d515-2bbc-4601-9134-734ee9916397)

Would it be possible to filter out 0 values if the previous value within that day was > 0 ?

**Comment by fsaris** [comment]
Can you provide some logs with debug enabled when this happens again? Want to check the measurement data (that should hold some more info) maybe we should use a different value or different type of statistic setting

**Comment by fsaris** [comment]
@marcelswinkels do you still see these issues?

**Comment by marcelswinkels** [comment]
@fsaris Thanks for your reply. I think it was an issue with the Zonneplan API. It hasn't reoccured since my initial report. I will keep an eye on it, and enable debugging if it happens again.

**Comment by fsaris** [comment]
Okay, closing this for now.
