### ISSUE TITLE
Current electricity tariff one hour off since Summertime

### ISSUE THREAD

**Issue by Paul1865** [fsaris/home-assistant-zonneplan-one#104]
The sensor sensor.zonneplan_current_electricity_tariff has the value of one hour ahead since summertime.

![image](https://github.com/fsaris/home-assistant-zonneplan-one/assets/17167055/e68d2f2c-ade5-4262-a9ca-47bebf86acfb)

**Comment by fsaris** [comment]
Is the issue still present? Or resolved it itself today?

**Comment by Paul1865** [comment]
Resolved itself :D !!
