### ISSUE TITLE
Gas price not updating anymore

### ISSUE THREAD

**Issue by renslinden** [fsaris/home-assistant-zonneplan-one#111]
I'm facing weird issues with the gas price for 2 weeks or so. I don't know what exactly happened since one of the latest versions but the gas price (both current and next price) behaves not as it should. 

It seems auto refreshing isn't working anymore at the time it should. Restarting HA or reloading the integration solves it...

**Comment by fsaris** [comment]
Can you provide some debug logs?

**Comment by fsaris** [comment]
Are you use the latest version? There are some issues fixed similar to what you mention

**Comment by renslinden** [comment]
Sorry, I had a some busy days. 

Currently it's working fine for me.

Seems Zonneplan did do something to the gas prices, they were quite late. Think they had problems with their source.
And since days the 'next gas price' arrives 3 o'clock midnight, while it was 6 o'clock in the evening...
