### ISSUE TITLE
Powerplay

### ISSUE THREAD

**Issue by krulkip** [fsaris/home-assistant-zonneplan-one#112]
Can i switch off my zonneplan inverter through home assistant.

**Comment by fsaris** [comment]
No currently not, is that possible using the app? With powerplay enabled you can let Zonneplan disable the inverter don't think you can do this your self.

**Comment by krulkip** [comment]
Yes you are correct. Only Zonneplan can do that remotely. But would be nice if dynamic electricity prices are negative.
    On Monday 22 April 2024 at 14:21:32 GMT+9, Frans Saris ***@***.***> wrote:  
 
 


No currently not, is that possible using the app? With powerplay enabled you can let Zonneplan disable the inverter don't think you can do this your self.

**Comment by fsaris** [comment]
closing as this is currently not provided as an option in the API
