### ISSUE TITLE
Detected blocking call to open inside the event loop (HA 2024.6)

### ISSUE THREAD

**Issue by hmmbob** [fsaris/home-assistant-zonneplan-one#117]
Got this in my logs on 2024.6.0b4:

> Detected blocking call to open inside the event loop by custom integration 'zonneplan_one' at custom_components/zonneplan_one/zonneplan_api/api.py, line 32: f = open(script_directory + '/../manifest.json') (offender: /config/custom_components/zonneplan_one/zonneplan_api/api.py, line 32: f = open(script_directory + '/../manifest.json')), please create a bug report at https://github.com/fsaris/home-assistant-zonneplan-one/issues

**Comment by hmmbob** [comment]
Beta 5 throws more verbose errors, copying here for your reference:

> Detected blocking call to open inside the event loop by custom integration 'zonneplan_one' at custom_components/zonneplan_one/zonneplan_api/api.py, line 32: f = open(script_directory + '/../manifest.json') (offender: /config/custom_components/zonneplan_one/zonneplan_api/api.py, line 32: f = open(script_directory + '/../manifest.json')), please create a bug report at https://github.com/fsaris/home-assistant-zonneplan-one/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 188, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 402, in _async_setup_component result = await task File "/config/custom_components/zonneplan_one/__init__.py", line 29, in async_setup api.AsyncConfigEntryAuth(aiohttp_client.async_get_clientsession(hass)) File "/config/custom_components/zonneplan_one/api.py", line 22, in __init__ super().__init__(websession) File "/config/custom_components/zonneplan_one/zonneplan_api/api.py", line 26, in __init__ "x-ha-integration": self._get_integration_version(), File "/config/custom_components/zonneplan_one/zonneplan_api/api.py", line 32, in _get_integration_version f = open(script_directory + '/../manifest.json')

**Comment by mrboogiee** [comment]
seems like I experience the same issue
