### ISSUE TITLE
sensor.zonneplan_current_usage Shows 0

### ISSUE THREAD

**Issue by StSaens** [fsaris/home-assistant-zonneplan-one#119]
The sensor “sensor.zonneplan_current_usage“ shows 0, while the other sensors do show data which correlates to the Zonneplan app. Is some additional device needed for this sensor to show data?

i have a contract with zonneplan and have their dongle connected to the P1 port. The zonneplan app shows valid data.

**Comment by fsaris** [comment]
This is the `Current electricity usage`, a value that (was) available when you have a energy contract with Zonneplan

**Comment by StSaens** [comment]
Uhm, but I do have an energy contract with Zonneplan. I also wrote this in my post. On 11 Jun 2024, at 18:55, Frans Saris ***@***.***> wrote:﻿
This is the Current electricity usage, a value that (was) available when you have a energy contract with Zonneplan

**Comment by fsaris** [comment]
I don't 🙂 

So I'm not able to validate if the value is still part of the API.

Maybe you can share some debug logging then I can check the data

**Comment by martijnrusschen** [comment]
if you're only interested in energy prices, there are many other options including:
- https://github.com/JaccoR/hass-entso-e
- https://github.com/custom-components/nordpool/

**Comment by StSaens** [comment]
I’ll get a Homewizard to log current power consumption.

**Comment by martijnrusschen** [comment]
okay, can confirm it's still working here:
![Screenshot 2024-06-11 at 20 53 36@2x](https://github.com/fsaris/home-assistant-zonneplan-one/assets/1412392/c44f6aee-13e8-40d2-88c8-07a3266a69df)

Does reloading the integration work?

**Comment by StSaens** [comment]
Deleted and re-installed the integration. See img. below.
Nothing in the logs either. 

I think the tops rows show some recent usage averaged over time. A homewizard should give me (near) real-time usage and per phase too. So I’ll go that way. 

![IMG_0254](https://github.com/fsaris/home-assistant-zonneplan-one/assets/11319160/97415b99-3e31-4fba-9f38-e790f16ef373)
