### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by geedsen** [fsaris/home-assistant-zonneplan-one#120]
I just added the integration via HACS. It just added it, did not ask for any info. But does not show any info either. How does it know which zonneplan customer I am?  My contract starts 25th of June. But I am really only interested in the hourly energy rates as I want to stop my solar panels when there are negative prices. I  can see them already in the app.  This is all I see: 
![image](https://github.com/fsaris/home-assistant-zonneplan-one/assets/1316595/3149b166-e663-4940-afbf-1acb3af7d727)

**Comment by fsaris** [comment]
You need to follow the setup steps https://github.com/fsaris/home-assistant-zonneplan-one?tab=readme-ov-file#setup

**Comment by geedsen** [comment]
![image](https://github.com/fsaris/home-assistant-zonneplan-one/assets/1316595/c7c49dac-3e6c-4f86-86f8-d35d3e96dfb4)
It did not ask for an email address. And I see in one of the other issues that I am not the only one with that problem.

**Comment by geedsen** [comment]
And I dont see anywhere an option to remove the Zonneplan "Device" from HACS, to see if I can do a reinstall.

**Comment by fsaris** [comment]
Are you sure you added the integration?

Installation has 2 steps:
- install integration through HACS
- setup/add integration in the HA configuration

Here a shortcut to the `Add integration` step https://my.home-assistant.io/redirect/config_flow_start/?domain=zonneplan_one

**Comment by fsaris** [comment]
> I just added the integration via HACS. It just added it, did not ask for any info. But does not show any info either. How does it know which zonneplan customer I am? My contract starts 25th of June. But I am really only interested in the hourly energy rates as I want to stop my solar panels when there are negative prices. I can see them already in the app. This is all I see: ![image](https://private-user-images.githubusercontent.com/1316595/338538415-3149b166-e663-4940-afbf-1acb3af7d727.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjM4MTEsIm5iZiI6MTcxODEyMzUxMSwicGF0aCI6Ii8xMzE2NTk1LzMzODUzODQxNS0zMTQ5YjE2Ni1lNjYzLTQ5NDAtYWZiZi0xYWNiM2FmN2Q3MjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMTYzMTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTNjMGZjMWNiZjFlZmRkMWY0MDk4MmY1ODg2ODFlYzJkMWU3NjY2NTg0NjdmNmRhMmQ0OGRlOGQxN2RmYzNiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XIzLCI7AfDUBhde4ojSF3Sm6jdiF7pJE_WZuUrx71Q8)

This is the status of the Zonneplan install package in HACS. This monitors for updates etc. This is not the Zonnedplan integration itself

**Comment by geedsen** [comment]
Ah. I missed that part. Now it works. Thanks!
