### ISSUE TITLE
Forecast unavailable

### ISSUE THREAD

**Issue by i6media** [fsaris/home-assistant-zonneplan-one#128]
I have an Energy Contract with Zonneplan, however the Forecast prices aren't available, but the current energy prices are.

How can I implement the forecast?

![Scherm­afbeelding 2024-07-03 om 11 26 52](https://github.com/fsaris/home-assistant-zonneplan-one/assets/14023039/8dabc61e-8e56-4b11-9df1-fc19a42ba287)

**Comment by fsaris** [comment]
Edit and enable each sensor you want

**Comment by i6media** [comment]
That dit the trick, thanks @fsaris
