### ISSUE TITLE
Daily reset for ‘sensor.electricity_production_costs_today’

### ISSUE THREAD

**Issue by vries-ict** [fsaris/home-assistant-zonneplan-one#129]
The value of ‘sensor.electricity_production_costs_today’ sometimes still has a value after 0:00 hours and then is unavailable until the energy production starts the next day. This behavior causes for instance a utility meter helper that is based on this sensor to start with the wrong value.
Can you please make it behave just like it’s counterpart ‘sensor.electricity_delivery_costs_today’ and have a daily reset to zero at 0:00 hours?

**Comment by fsaris** [comment]
Both sensors are setup equal and use the same property to trigger a reset on the new day.
So they should already behave the same.

Can you provide the graphs for both sensors?

**Comment by fsaris** [comment]
@vries-ict can you test the main branch? Added a fallback to zero when sensor gets unavailable

**Comment by vries-ict** [comment]
Thanks for your swift action. I would really like to test for you, Sorry, I don't know how to do that yet, but I would like to learn. Can you point me in the right direction or documentation. Thanks.

**Comment by vries-ict** [comment]
Over the last couple of day ‘sensor.electricity_production_costs_today’ had a daily reset to zero as you intended. That also solved the issues I had with calculating net costs. Thanks @fsaris !

**Comment by fsaris** [comment]
https://github.com/fsaris/home-assistant-zonneplan-one/tree/2024.9.0
