### ISSUE TITLE
Add cycles (batterijcycli) to available sensors after update 2024-07-17

### ISSUE THREAD

**Issue by TFhdKi95ae8L** [fsaris/home-assistant-zonneplan-one#131]
Latest update also provides battery cycle counter.
Can you add that to the available sensors as well?
In the app it is available under "systeem"
Thanks!

**Comment by fsaris** [comment]
Can you provide some debug logs to provide the correct name for the sensor value

**Comment by TFhdKi95ae8L** [comment]
Comfortably at home again, and cannot find anything in the logs.
Can you share a making a debug log for dummies here?

**Comment by fsaris** [comment]
1. Goto https://my.home-assistant.io/redirect/integration/?domain=zonneplan_one and enable debug logging 
2. Goto https://my.home-assistant.io/redirect/logs/ scroll down and click "Laad volledige logboeken"

Every 5min it should log the API calls

**Comment by TFhdKi95ae8L** [comment]
See pull request #134 
Note that I am a novice at best, so please triple check my work ;-)

**Comment by fsaris** [comment]
Will give it a look/try in one of the next daya

**Comment by fsaris** [comment]
@TFhdKi95ae8L this cycle is a number that only increases? As in the total number of (loading) cycles that where performed?

**Comment by TFhdKi95ae8L** [comment]
Yes, should be increasing only, everytime the battery completes one nominal capacity cycle.

**Comment by fsaris** [comment]
@TFhdKi95ae8L can you give the main version a try?

**Comment by TFhdKi95ae8L** [comment]
Works!
![image](https://github.com/user-attachments/assets/ff1c8934-df8b-4569-b249-ff795e115314)

**Comment by TFhdKi95ae8L** [comment]
I see you also implemented the self consumption as a sensor. Great job!

**Comment by fsaris** [comment]
Will keep the issue open until it's part of an official release/version

**Comment by fsaris** [comment]
https://github.com/fsaris/home-assistant-zonneplan-one/tree/2024.9.0
