### ISSUE TITLE
make earnings available 

### ISSUE THREAD

**Issue by NLfrans** [fsaris/home-assistant-zonneplan-one#133]
Is it possible to make earnings available

- **vandaag (euro's)** Cost today
- **afname (kWh)** Grid Consumption today
- **afname (ct)** Grid Consumption Cost on average
- **teruglevering (kWh)** Feed-in today
- **teruglevering (ct)** Feed-in Cost on average

with and without Energiebelasting (Energy taxation) option

![IMG_4739](https://github.com/user-attachments/assets/cb5ce73c-2a60-4057-97ce-7832c7d392dd)

**Comment by NLfrans** [comment]
i'm not sure if you provide this information but a lot of sensors are not available

 <img width="672" alt="Scherm­afbeelding 2024-07-26 om 13 12 04" src="https://github.com/user-attachments/assets/a4b6f7df-8829-4cb2-a8f3-ddb709407cfe">

**Comment by fsaris** [comment]
Did you try to enable them 🙂

Edit the sensor and toggle the enable setting + hit save

**Comment by fsaris** [comment]
Aren't most of the requested sensors already available?

**Comment by NLfrans** [comment]
I didn’t know.

But it’s work

![IMG_4797](https://github.com/user-attachments/assets/20dc863f-1fa5-4567-89db-f128172b8cce)


Looks like 👍😎

![IMG_4798](https://github.com/user-attachments/assets/6d3429f1-f5fb-4d61-b72e-bd3c4788d57e)

**Comment by NLfrans** [comment]
By enabling the entity i made it work
