### ISSUE TITLE
Restart resets meters costs

### ISSUE THREAD

**Issue by voidzero** [fsaris/home-assistant-zonneplan-one#135]
Hi,

After a restart, `electricity_meter_energieverbruik_tarief_1_cost`, `electricity_meter_energieverbruik_tarief_2_cost` and `sensor.gas_meter_gasverbruik_cost` go back to zero. Is it possible to reset them every first of the month and maintain the values otherwise?

**Comment by fsaris** [comment]
Do you se a reset or a temporary 0 or unknown value?

**Comment by voidzero** [comment]
It just goes back to zero. For example, I just updated to 2024.9.1 from 2024.9.0:

![image](https://github.com/user-attachments/assets/4fab80db-448e-4aad-a110-c3326def6c5a)

**Comment by fsaris** [comment]
Aren't these you're own utility sensors?

**Comment by voidzero** [comment]
Argh. You're right, what a dumb mistake. 🤦🏻‍♂️ I apologize.
