### ISSUE TITLE
Hourly vs. Minute-to-Minute Price Updates for sensor.zonneplan_current_electricity_tariff?

### ISSUE THREAD

**Issue by joopdo** [fsaris/home-assistant-zonneplan-one#139]
Hey, thanks for this addon. Just a quick question on which I could not find the answer online. When I review `sensor.zonneplan_current_electricity_tariff` I observe different prices every few minutes, but in the app, I see different prices per hour.
I expected the prices to change in home-assistant-zonneplan-one on an hourly basis as well.
Is home-assistant-zonneplan-one more specific with these minute-to-minute prices, or am I looking at some sort of misconfiguration.

HomeAssistant with Zonneplan-one:
![Screenshot from 2024-09-08 13-22-31](https://github.com/user-attachments/assets/d8ef5beb-fa76-4617-aedc-0afa90bf1054)

Zonneplan app:
![Screenshot from 2024-09-09 08-34-45](https://github.com/user-attachments/assets/e2fdf872-f5db-48c9-b783-d9f6e88c20f7)

**Comment by joopdo** [comment]
Perhaps it was because I was running `0.0.17"`. Updated just now, fingers crossed.

**Comment by fsaris** [comment]
Just checked my own stats and I only see 1 update each hour.
Did you hover the graph and check the times the of each change.

**Comment by joopdo** [comment]
Thanks @fsaris I see I was zoomed out a lot on that first screenshot. Closing
