### ISSUE TITLE
Error: Config flow could not be loaded

### ISSUE THREAD

**Issue by Cyb0rg42** [fsaris/home-assistant-zonneplan-one#14]
I've use the manual method to install the zonneplan_one integration.  Restarted HomeAssistant and my next step was to configure the zonneplan_one integration. When I select the integration I get the error: Config flow could not be loaded.

The home-assistant.log file contains the following error:
 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration zonneplan_one: cannot import name 'SensorDeviceClass' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)

Any idea what is going wrong?

I'm running version 2021.9.5

**Comment by fsaris** [comment]
Please use version 0.0.7 or earlier. https://github.com/fsaris/home-assistant-zonneplan-one/releases/tag/0.0.7

Latest version requires HA 2021.12
