### ISSUE TITLE
8 hours

### ISSUE THREAD

**Issue by janbart82** [fsaris/home-assistant-zonneplan-one#141]
In your description I read that electricity prices are 8 hours ahead. But in the app it is the day ahead, renewed at 2 o'clock. Can you explain the difference?
Thanks,
Jan

**Comment by fsaris** [comment]
They shouldn't be 8 hours ahead but the next 8 hours. For these there is a seperate sensor for each hour.

The full forecast is available as attribute of the "Electricity tariff" sensor 
See readme

> Current Zonneplan Electricity tariff: €/kWh
The full Electricity forecast is available as a forecast attribute of this sensor

**Comment by janbart82** [comment]
Thank you Frank, somehow I have not seen these words in the readme.
However, I still do not understand what you then mean with the next
sentence in the readme:
8 hours forecast of Zonneplan Electricity tariff: €/kWh (default disabled,
available when you have a energy contract).

Perhaps you can explain this to me. I am from Holland, so Dutch will do if
you are from Holland too.

Greetings,
Jan

Op wo 18 sep. 2024 19:00 schreef Frans Saris ***@***.***>:

**Comment by fsaris** [comment]
Er zijn 8 sensoren beschikbaar als je een Zonneplan contract hebt die prijs voor de komende de 8 uur tonen. 

`Forecast tariff hour 1` zijn de kosten voor koment uur, `Forecast tariff hour 2` voor het uur erna etc.

Deze sensoren zijn standaard niet ingeschakeld. Als je deze waardes zo als 8 losse sensoren wilt hebben zul je ze dus moeten inschakelen.

**Comment by janbart82** [comment]
Dank je Frans, ik denk dat ik over een poosje aan de slag ga met de Home
Assistant en de Zonneplan integratie. Lijkt me heel interessant icm
warmtepomp.

Mvg,
Jan

Op zo 29 sep. 2024 10:49 schreef Frans Saris ***@***.***>:
