### ISSUE TITLE
Data refresh interval time

### ISSUE THREAD

**Issue by Dominic-070** [fsaris/home-assistant-zonneplan-one#142]
I noticed that the Zonneplan integration retrieves data once every 5 minutes from a server where the data is refreshed once every 5 minutes. The data on the server is refreshed every few seconds after the full 5 minutes. If you just happened to restart Home Assistant or the Zonneplan integration at 19:09, your data is always 4 minutes behind. The data in the energy dashboard is therefore even more incorrect.

Can the integration instead of the moment of start-up and then pull every 5 minutes look at sensors the last_update sensors and refresh based on that or on the full 5 minutes (+ approx. 40 seconds)?

See also: https://gathering.tweakers.net/forum/list_message/80192180#80192180

**Comment by fsaris** [comment]
I didn't implement this because the Zonneplan servers probably will not like this if all integrations call the API around the same time. See for example https://github.com/fsaris/home-assistant-zonneplan-one/discussions/89

**Comment by Dominic-070** [comment]
Thanks for your awnser.

**Comment by Dominic-070** [comment]
Awesome! I think it will be updated at a high frequency: all sensors with energy or power, battery SoC, and the current energy price so the energy dashboard can update correctly. All statics, like yearly or monthly, first measurements, can be updated at a much lower frequency.

**Comment by fsaris** [comment]
I did a test run with fetching the P1 Electricity data every 60 seconds. Yes you get every 2 to 3 minutes a new response but the values only update every 5 minutes. So not sure if it makes sense to poll the API more often then once every 5 minutes

**Comment by martijnrusschen** [comment]
Chargepoint sensors might need a faster refresh rate as well. Looking at the app, the data is more real time and not just a 5 min interval.

**Comment by fsaris** [comment]
@martijnrusschen will update them for now, while testing the new beta, but doesn't seem that the data is really updated more often then every 5 minutes.

Maybe you can check your results by testing the beta https://github.com/fsaris/home-assistant-zonneplan-one/releases/tag/2026.1.0b2

**Comment by fsaris** [comment]
@Dominic-070 @martijnrusschen don't really see other intervals then once every 5 minutes. Do you see any when you switch to https://github.com/fsaris/home-assistant-zonneplan-one/releases/tag/2026.1.0b3
