### ISSUE TITLE
Electricity consumption low-normal-high are unknown

### ISSUE THREAD

**Issue by M20Lucas** [fsaris/home-assistant-zonneplan-one#145]
With the last update, the three sensors that display the three different electricity consumption by tariff group, are all stuck on 'unknown'. Rebooting HA or the integration won’t work to resolve the problem…

![Scherm­afbeelding 2024-10-08 om 16 38 32](https://github.com/user-attachments/assets/36cc690f-2498-41bd-b6bb-e0b562623fe9)

**Comment by fsaris** [comment]
Looks that these values aren't available anymore. I'm not able to find them in the app.

Need to double check the API responses

**Comment by fsaris** [comment]
I removed the sensors as they are not part of the api response anymore
