### ISSUE TITLE
Zonneplan Electricity production/delivery costs today

### ISSUE THREAD

**Issue by geedsen** [fsaris/home-assistant-zonneplan-one#147]
What exactly is the "Zonneplan Electricity production costs today" and "Zonneplan Electricity delivery costs today"? My guess is that the total of these two would amount in what I see in the Zonneplan App as my total cost of today. But it comes nowhere near.
![image](https://github.com/user-attachments/assets/4ae3253f-17ae-42e0-8e61-f148d95045e4)

![image](https://github.com/user-attachments/assets/794df558-4a55-4027-b5a4-57c1b9c68350)

**Comment by hcassus** [comment]
I'm having a similar issue with my provider (not zonenplan) so try and check if the costs are already taking fixed provider costs into account or if it is just the Energy costs/compensation.

**Comment by fsaris** [comment]
To be honest I don't really know what value exactly represents. It's part of the API response and was used in the older version of Zonneplan APP kept if for now as maybe long(er) time users are still relying on the values.
