### ISSUE TITLE
8-hour forecast werkt niet

### ISSUE THREAD

**Issue by AdventurePandah** [fsaris/home-assistant-zonneplan-one#149]
Ik heb Zonneplan geinstalleerd. Heb ook een energiecontract bij Zonneplan. Wanneer ik de 8-hour forecast wil activeren, zie ik enkel de geschiedenis van de afgelopen 8 uur.

Meerdere manieren geprobeerd om de gegevens eruit te krijgen. Echter krijg ik het niet voor elkaar. 

In de Zonneplan app is het mogelijk om 24h vooruit te kijken in de tarieven. Mooiste zou zijn als ik deze 24h kan ophalen om zo op het goedkoopste moment mijn wasmachine te activeren.

Hoor graag wat de mogelijkheden zijn en of dit om een daadwerkelijke bug gaat.

**Comment by fsaris** [comment]
Voor de volledige (voor zover bekend, ook in de app is het niet altijd 24uur) forecast zie bijv:

- https://github.com/fsaris/home-assistant-zonneplan-one/discussions/41
- https://github.com/fsaris/home-assistant-zonneplan-one/discussions/47
