### ISSUE TITLE
Gas last measured consumption unknown

### ISSUE THREAD

**Issue by Ascathon** [fsaris/home-assistant-zonneplan-one#15]
Since a few days, the sensor "sensor.zonneplan_p1_gas_last_measured_consumption" returns no value and stays on unknown. Using the latest version of all components. Cannot exactly recall when it started, so many december updates but it wasn't an HACS/integration update.

Also reinstalled the integration, it is still on unknown. Consumption today and last measured work just fine.

![image](https://user-images.githubusercontent.com/21990236/147050390-3557b78c-894b-4ab4-93b3-5a1ac0475deb.png)

**Comment by fsaris** [comment]
This value was removed from the API. Will remove it from the integration in one of the next days

**Comment by Ascathon** [comment]
Oh damn, that is a shame for my cool graphs. :(

**Comment by fsaris** [comment]
It was more or less the usage of the last hour. Could bring that back using a different way but not sure if that's useful.

You could also create a statistics sensor using the today value as input :)

**Comment by Ascathon** [comment]
I don't know all fancy stuff yet. Developers thought of so many stuff to customize data. Thanks.
You can close the issue or keep it if you want to track the removal of that value. Though removal doesn't "fix" the issue.

**Comment by fsaris** [comment]
Sensor is removed with https://github.com/fsaris/home-assistant-zonneplan-one/commit/64b0ae95c84faad50b256bc3070d6edb032d621c
