### ISSUE TITLE
opnieuw configureren van integratie werkt niet

### ISSUE THREAD

**Issue by siegfried2003** [fsaris/home-assistant-zonneplan-one#152]
Beste,

Sinds vrijdag werkt de integratie niet meer via homeassistant. Er wordt gevraagd voor herconfiguratie en als ik dat doe krijg ik melding config flow kon niet geladen worden. Ook als ik de integratie volledige verwijder en een oudere versie installeer is het niet mogelijk om opnieuw in te loggen. Ik krijg dan melding un known error occurred. Ik heb gezien dat wellicht api geblokkeerd kan zijn voor mijn account. Maar de app thuis via wifi werkt gewoon. Hopelijk is er iets over bekend

<img width="750" alt="Scherm­afbeelding 2024-12-08 om 13 19 22" src="https://github.com/user-attachments/assets/804840c8-d0e4-4887-8f0a-394194928959">
<img width="637" alt="Scherm­afbeelding 2024-12-08 om 13 21 50" src="https://github.com/user-attachments/assets/e06927c3-2a80-4c1a-b225-a2cc940698ad">

**Comment by fsaris** [comment]
Uiteindelijk gelukt?
