### ISSUE TITLE
Unable to login again after authentication expired

### ISSUE THREAD

**Issue by Phontana** [fsaris/home-assistant-zonneplan-one#18]
I've had a notification from Home Assistant a few times now, stating that an integration needed a renewal of the configuration. The integration mentioned is this Zonneplan integration. Up to this week I was able to re-authenticate the integration by entering my email address again and everything was fine again. However, from this week I get the following message in the logs:

```Failed 422, message='Unprocessable Content', url=URL('https://app-api.zonneplan.nl/auth/request')
Traceback (most recent call last):
  File "/config/custom_components/zonneplan_one/config_flow.py", line 87, in async_step_auth
    self._token = await self.flow_impl.async_request_temp_pass(self._email)
  File "/config/custom_components/zonneplan_one/api.py", line 87, in async_request_temp_pass
    return await self._api.async_request_temp_pass(email)
  File "/config/custom_components/zonneplan_one/zonneplan_api/api.py", line 39, in async_request_temp_pass
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 422, message='Unprocessable Content', url=URL('https://app-api.zonneplan.nl/auth/request')
```

I'm not able to authenticate the Zonneplan integration anymore. The issue might be related to [this issue](https://github.com/fsaris/home-assistant-zonneplan-one/issues/16) in some way.

**Comment by Phontana** [comment]
Deleting and adding the integration again fixed the issue for now, but it still looks like a stability issue in this integration.

**Comment by fsaris** [comment]
Strange, response `422, message='Unprocessable Content'` implies that the request was invalid. Token format incorrect or something.

Had last month also a few times that I needed to re-authenticate but that went okay without any issues.

Maybe we should also clear the token to force re-authentication when a 422 code is returned.

**Comment by Phontana** [comment]
I had the same experience, had to re-authenticate a few times which eventually seemed to lead to this error. Since deleting and adding the integration again fixed it, I think clearing the token would have the same effect.

**Comment by erno1978** [comment]
Same issue here. It keeps nagging about a wrong e-mail address for sending the link. But it did work for several days...

**Comment by Phontana** [comment]
Had the same issue today. It turned out the Zonneplan API was offline or having issues, because I noticed the Zonneplan app was not working either. I was just able to te-authenticate and now it works again.

Is it the case that the integration thinks that te-authentication is needed when Zonneplan API throws an error?

**Comment by fsaris** [comment]
Yes, currently every ClientResponseError results in a new authentication flow. Will change that so this only happens on status 403

**Comment by erno1978** [comment]
Thanks @fsaris! My issue resolved itself automatically, but it's great to see that you keep improving it. I'm a happy user! Keep up the good work!

**Comment by fsaris** [comment]
resolved in https://github.com/fsaris/home-assistant-zonneplan-one/releases/tag/0.0.10
