### ISSUE TITLE
Could not find p1_installation of p1_installation

### ISSUE THREAD

**Issue by Phontana** [fsaris/home-assistant-zonneplan-one#19]
I get the following warning in the logs of Home Assistant:

```
Logger: custom_components.zonneplan_one.coordinator
Source: custom_components/zonneplan_one/coordinator.py:116 
Integration: Zonneplan ONE 
First occurred: 11:27:13 (1 occurrences) 
Last logged: 11:27:13

Could not find p1_installation of p1_installation
```

What can I do to resolve this?

**Comment by fsaris** [comment]
Do you have a p1 dongle of zonneplan?

Does this warning only happen once after restart?

**Comment by Phontana** [comment]
I don't have a P1 dongle, but I have a similar device in my Zonneplan One inverter. Zonneplan doesn't use the older USB AOI modules anymore, but they moved towards their own solution for collecting data for solar inverters. So I got a new device which they also call 'Zonneplan Connect' but with a RJ45 connector for RS485 connections instead of RJ11 for P1 connections.

**Comment by fsaris** [comment]
this warning is there by intention. It will only report once when the integration starts
