### ISSUE TITLE
[Question] plans/possibilities for current energy consumption integration

### ISSUE THREAD

**Issue by Broekman** [fsaris/home-assistant-zonneplan-one#2]
Hi Frans,

First of all, thanks for this integration, much appreciated! Are there any plans (or at least possibilities) to also in include the energy consumption in the integration. At the moment the Zonneplan device (in the P1 port of smart meter) is just hanging there doing nothing (although I can see it in the Zonneplan app).

Thanks and have nice weekend,
Stefan

**Comment by fsaris** [comment]
Hi, I personally don't have the P1 device so I don't get that data in my app.

To reverse engineer the correct api calls I would need to get access to a account with P1 data to check what calls are made.

Maybe you can give me temporary access to your account with the "Deel de app met je gezin" option. So I can check the api calls.

**Comment by Broekman** [comment]
Hi, that would be great, many thanks. Can you send me an email to which I can add the family share. Also let me know if you need anything else or if I have to test something.

**Comment by fsaris** [comment]
Please contact me via DM on https://community.home-assistant.io/u/minifranske

**Comment by fsaris** [comment]
Added support for the P1, not sure about all values will let it run for a while to see if I added the correct labels to the available values. To try this you self install the latest main version https://github.com/fsaris/home-assistant-zonneplan-one#installing-mainbeta-version-using-hacs

**Comment by Broekman** [comment]
Many thanks, much appreciated! Overall seems to be working just fine. Below some small remarks:

Electricity today
- Values OK
- Name: perhaps change to 'Energy consumption today'
- Icon: currently mdi:power; perhaps change to mdi:flash? (mid:power is a power button).

Electricity delivery
- Values OK (verified with home meter vs what Zonneplan reports back)
- Name: perhaps change to 'Energy consumption' - delivery feels wrong 😄 
- Icon: same as 'electricity today'

Electricity production
- Name: perhaps change to 'Energy production'
- Will check values tomorrow, at the time of installing I was already consuming more than I was producing always 0.
- Icon: same as 'electricity today'

Electricity average
- Name: perhaps change to 'Energy consumption daily average' to align with the others
- Icon: same as 'electricity today'
- Looks like the result of (daily consumption / hours) although I only have ~1 hour of data the moment, so not 100% sure.

Last/first measured
- If you agree with the name changes; align with above ^

Gas
- All OK, maybe also add consumption or something to the name. Other than that no remarks.

**Comment by fsaris** [comment]
Ah, it was `mdi:flash` I was looking for indeed 😄 

Are the gas values in the correct unit? Looked to me that is was off by a factor of 1000. But not exactly sure.

Will check the naming later this weekend.

**Comment by Broekman** [comment]
Oops, you're right. Gas is indeed of by a factor of 1000.

**Comment by fsaris** [comment]
@Broekman any idea if `Electricity average` is the average daily consumption? Or maybe an average of `(consumption + solar power) - production` so the "real" current consumption.

**Comment by fsaris** [comment]
I updated some of the labels and icons

**Comment by Broekman** [comment]
Hi Frans,

Thanks for the update.

Looks like the average is the value used by Zonneplan for the live power value in their app (because I don't buy energy from them it's not shown in the app anymore). I created a sensor myself yesterday with a simplistic (P1 consumption - P1 production) which results in roughly the same value although it looks like Zonneplan does some time based average on this as it always differs ~5-20 watts.

Also added a sensor: (solar yield - production + consumption) to get the actual needed power (i.e. what my devices actually use).

Also a note on the actual gas usage, it looks a bit behind. E.g. today at 7:32 my thermostat reported 100% heating and gradually reduced heating power till 9:02 (8:07 <30%). Initial gas spike was at 8:07 and a giant spike was at 9:11, while my thermostat was already <30% from 8:07 (no hot water used elsewhere this morning). At 10:07 the giant spike went down again while my thermostat was already idling/low power around 8:15. When I see a spike again I will check the actual values on my meter (can also test by just increasing my temp later today). Overall daily gas usage/increases does look OK (divided by 1000). This is of course not on your side but just as a note.

**Comment by fsaris** [comment]
regarding gas usage; looks like this is reported only every hour with some additional delay. If you look at the hour graph in the app the values seem to match. And that graph is also behind.

**Comment by Broekman** [comment]
Yes, I also noticed the high interval so that's explainable.

Regarding the average value, I'm quite sure its average since last report. It also averages short spikes (e.g. coffee machine) but goes back to normal on the next update.

**Comment by Broekman** [comment]
Hi Frans,

All seems to be OK and didn't have any issues so far, so I think we can close the ticket? I will leave the family access to my Zonneplan account up for a few more weeks (or longer/shorter, whatever you need). Many thanks for the quick addition 👍 If you need anything, you can contact me through e.g. a PM on Home Assistant.

**Comment by fsaris** [comment]
Hi Stefan,

Your welcome.

Zonneplan contacted me after they saw the discussion here  and send me a `Zonneplan Connect` module so I can test this with my own data in the near future :)
