### ISSUE TITLE
Sensor zonneplan_current_gas_tariff has a gap everyday.

### ISSUE THREAD

**Issue by loedeman** [fsaris/home-assistant-zonneplan-one#20]
Hi,

The sensor.zonneplan_current_gas_tariff sensor has a gap in its data every day (about the first 4 hours of the day). Is there an explanation for this behavior? I think I would at least like to maintain the last gas price in this scenario, because the sensor is currently unusable for energy dashboard pricing…

![95C393E1-496A-42B0-AE03-F71E397B1FE4](https://user-images.githubusercontent.com/355132/162765214-e57c4f27-31cf-4075-9fd7-253c735a81ce.jpeg)

**Comment by fsaris** [comment]
Not sure yet if this is an issue of the integration. It doesn't seem to log anything at that moment so the graph should connect the lines.

**Comment by fsaris** [comment]
looks like an issue in the graph not in the data

**Comment by fsaris** [comment]
Looks related to #17. There are indeed `None` values delivered by the API.

**Comment by fsaris** [comment]
Fixed with https://github.com/fsaris/home-assistant-zonneplan-one/releases/tag/0.0.11
