### ISSUE TITLE
Yield yearly

### ISSUE THREAD

**Issue by windvanger** [fsaris/home-assistant-zonneplan-one#21]
I miss the yield yearly value in your Zonneplan One integration. Is it possible to add this value?
The Zonneplan integration is very nice!

**Comment by fsaris** [comment]
Not sure if the value is available. But the idea is to use the HA energy dashboard for this

**Comment by windvanger** [comment]
Thank you for your comment. For future energy measurements this is true, but for past measurements not. I use the yearly yield to calculate the Specific yield (kWh/kWp) on my location. As this is calculated per year it is very useful to get the yearly yield of Zonneplan.

**Comment by fsaris** [comment]
You can use the [Utility Meter - Home Assistant](https://www.home-assistant.io/integrations/utility_meter/) to create a year sensor
