### ISSUE TITLE
Change update interval "Zonneplan last measured value"

### ISSUE THREAD

**Issue by W13N3N** [fsaris/home-assistant-zonneplan-one#23]
Hi Frans,

First of; thanks for this awesome Zonneplan integration voor HA!! It works really well and provides me with the right information for my (daily) energy dashboard!

I recently installed the Power Flow Card addon which provides me with my current power consumption, taking account the total amount W/KW produced bij my solar panels at that time. Therefore i use the sensor "Zonneplan last measured value". Because my grid usage/production sensors are updating every second, and the "Zonneplan last measured value" only updates every 5 minutes, my results aren't that accurate. Is there a way to change the update frequency of the "Zonneplan last measured value" sensor?

Kind regards,
Frank

**Comment by fsaris** [comment]
The integration polls every 120 seconds the API for updates (https://github.com/fsaris/home-assistant-zonneplan-one/blob/935033492e894bec2a860f78b7714e26d5eb1b9a/custom_components/zonneplan_one/coordinator.py#L31)

So increasing the interval will not help because Zonneplan just doesn't provide more accurate data.

**Comment by W13N3N** [comment]
thanks for your quick reply!

But when i open the sensor, the refresh time increases to 5min and then starts over again. So 2 min already woud be better then 5? But what could be the reason my sensor isn't updating every 2min (120sec)?

**Comment by W13N3N** [comment]
![image](https://user-images.githubusercontent.com/19149185/197516771-d1817879-858d-47ac-836d-1e2a01af8613.png)

You also can see it in the logbook it only polls every 5min.

**Comment by fsaris** [comment]
No, you only get a new value every 5min.

And it only updates if there is a new value
