### ISSUE TITLE
401 message=Unauthorized

### ISSUE THREAD

**Issue by kranendijk** [fsaris/home-assistant-zonneplan-one#24]
Hi,

I received a message one of my integrations needed updating. The Zonneplan One integration showed a 401 error in the log. After resending/re-validating the email address the integration works fine again.
Why do I get this error? No changes were made to the email address at Zonneplan.

This is what is in the log, running latest versions of HA (on SD) and integrations including HACS.

`Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.zonneplan_one.coordinator
Source: helpers/update_coordinator.py:151 
Integration: Zonneplan ONE (documentation, issues) 
First occurred: 11:40:04 (1 occurrences) 
Last logged: 11:40:04

Authentication failed while fetching zonneplan_one data: 401, message='Unauthorized', url=URL('https://app-api.zonneplan.nl/user-accounts/me') `

**Comment by fsaris** [comment]
Had the same today. Looks like a hick-up on the side of Zonneplan.
