### ISSUE TITLE
Current gas price is dropping to 0 every night.

### ISSUE THREAD

**Issue by renslinden** [fsaris/home-assistant-zonneplan-one#26]
Hello,

After midnight the current price is dropping to 0 till the new price is available. In my assumption this is wrong because of the Energy dashboard.

Now it's calculating the gas price during those hours with a gas tariff of 0 euro. Which shouldn't of course.

Another side note, the new price is valid from 06.00 AM in the morning, isn't it? Then i expect the current price sensor changed around the clock of 06.00 AM and not already around the clock of 04.00 AM.

Maybe it's an idea to introduce a new sensor for the hours the price is already known but not valid yet. Something like _sensor.zonneplan_new_gas_tariff_

![Screenshot_2022-11-15-07-28-31-04_c3a231c25ed346e59462e84656a70e50.jpg](https://user-images.githubusercontent.com/8656122/201843722-5e5a1128-9d20-404b-9846-2105f129e0e9.jpg)

**Comment by fsaris** [comment]
Need to check the exact API response for this.

Could be there is no value at all between 0h and 4h.

I'm not buying energy from Zonneplan. But if you are sure what the "rules" are regarding the price and when it's applicable it should be possible to build this in the integration

**Comment by loedeman** [comment]
It is the same in the Zonneplan app. The gas price should remain the same until the next day price takes effect. This is not at 12AM but at 6AM CET.

This is an excerpt from the documentation for TTF Day Ahead: _The Day-Ahead contract (DA) is a strip of a single gas day from the next weekday at 06:00 (CET) to 06:00 (CET) on the following calendar day._
Source: https://www.theice.com/products/45436633/Dutch-TTF-Natural-Gas-Daily-Futures

**Comment by graafish** [comment]
I added a sensor to my system to fix the gap and it works with the energy dashboard.

```
- sensor:
    - name: zonneplan current gas tariff fix"
      unit_of_measurement: "EUR/m³"
      state: >-
        {% if is_state('sensor.zonneplan_current_gas_tariff', 'unknown') or is_state('sensor.zonneplan_current_gas_tariff', '0') %}
          {{ states('sensor.zonneplan_current_gas_tariff_fix') }}
        {% else %}
          {{ states('sensor.zonneplan_current_gas_tariff') }}
        {% endif %}`
```

**Comment by loedeman** [comment]
Nice workaround, thanks!

**Comment by fsaris** [comment]
Do we know if the value is `unknown` or `0` during the night? 
Looks that this change isn't correct https://github.com/fsaris/home-assistant-zonneplan-one/commit/a27ab2a0ec6485ba5900cea70dc2ab69859ebf6e that should have prevented it from going to 0. Or we really got 0 from the api

And only fixing this isn't enough right? It should also update at 6h instead of 4h

**Comment by graafish** [comment]
My solution was a quick fix. I thought the value was `0` because that's what showing in the graph.
Didn't know the price starts at 6am so if it does it needs a fix too.
Nice you're looking into this.

**Comment by wishmaster1984** [comment]
Would be great if this can be fixed. Thanks Frans for all your great work.

**Comment by fsaris** [comment]
Okay, in current master the 0 values are gone during 0:00 and +/- 4:00. 

Currently looking into only updating the gas tariff once a day at 6:00

**Comment by fsaris** [comment]
Current main version updates the gas tariff once a day at 6

**Comment by loedeman** [comment]
Sounds great, thanks. I just changed the HACS repo to main, hope to see the new behavior tomorrow 😀👍!

**Comment by fsaris** [comment]
Released a new version with the feature https://github.com/fsaris/home-assistant-zonneplan-one/releases/tag/0.0.13

**Comment by loedeman** [comment]
Thanks! I had some trouble reproducing it because I rebooted HA at the wrong time 🤗. But confirming it works indeed, nice!!!

**Comment by renslinden** [comment]
Looks good, thank you for the effort @fsaris!
