### ISSUE TITLE
Current electricity price seems to be yesterday's 

### ISSUE THREAD

**Issue by Bodmoor** [fsaris/home-assistant-zonneplan-one#29]
Hello,

The current price of electricity is incorrect. The prices displayed today match yesterday's prices. The sensor with the faulty data is sensor.zonneplan_current_electricity_tariff

![Screenshot_20221127-094106](https://user-images.githubusercontent.com/18680317/204126342-373fceef-6315-46be-ada3-2fb6a90290c1.png)

![Screenshot_20221127-094157](https://user-images.githubusercontent.com/18680317/204126359-2c842584-4528-46c2-aebb-da219fd79a67.png)

Yesterday's price:
![Screenshot_20221127-094305](https://user-images.githubusercontent.com/18680317/204126411-f00a4ce3-fd70-4c4a-bb67-279b833420de.png)

Kind regards,
Paul Segerink

**Comment by tieskuh** [comment]
What version are you running? Should be fixed in the latest version.

**Comment by Bodmoor** [comment]
Ah my bad, I was running 0.0.11 and did not see the update, thanks!
