### ISSUE TITLE
Highest_yield_at value should be a date (and read in CET)

### ISSUE THREAD

**Issue by tvandergeer** [fsaris/home-assistant-zonneplan-one#3]
Currently the highest_yield_at value is presented as a date. In our case:
```
2021-04-10 22:00:00+00:00
```
At first I thought that the highest recorded value was at April 10 around 22:00, but actually April 10 was a very bad day (in terms of solar energy production). Turns out that you should read this value as a date. The timestamp is in UTC time and the CET time (with DST) is +2 hours. In this case it would be 2021-04-11 00:00:00. And that is correct. Up until now April 11 2021 was the best day.

![image](https://user-images.githubusercontent.com/1439892/114449142-b52e1400-9bd4-11eb-919b-921da4520c8d.png)

**Comment by fsaris** [comment]
Need to give it a look later. As this value is returned directly with this timezone by zonneplan.

**Comment by fsaris** [comment]
Think I will go for the same approach as HA does for `sensor.date` https://www.home-assistant.io/integrations/time_date/ 

Will assume the date we get from the api should be in the `Europe/Amsterdam` timezone and format the timestamp to a date based on that

**Comment by tvandergeer** [comment]
Yes, that looks like a good solution! Is this something that each user needs to do manually or is it possible to make this part of the integration?

**Comment by fsaris** [comment]
Current main should give better dates https://github.com/fsaris/home-assistant-zonneplan-one#installing-mainbeta-version-using-hacs

**Comment by fsaris** [comment]
ok, https://www.home-assistant.io/integrations/sensor/#device-class `timestamp` works better :)
