### ISSUE TITLE
Retrying setup: 403, message='Forbidden'

### ISSUE THREAD

**Issue by aNtiihEks** [fsaris/home-assistant-zonneplan-one#32]
Retrying setup: 403, message='Forbidden', url=URL('https://app-api.zonneplan.nl/connections/xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx/summary')

Logger: homeassistant.config_entries
Source: config_entries.py:1089
First occurred: 20:56:41 (3 occurrences)
Last logged: 20:58:03

Config entry 'emailaddress@gmail.com' for zonneplan_one integration not ready yet: 403, message='Forbidden', url=URL('https://app-api.zonneplan.nl/connections/xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx/summary'); Retrying in background

Even tried to recreate the api links, same result. 

Thanks in advance

Home Assistant 2022.11.5
Frontend 20221108.0 - latest

**Comment by aNtiihEks** [comment]
Also did reinstalling the intergration without luck.

**Comment by fsaris** [comment]
Looks like Zonneplan changed the API. Need to check the api calls (sniffing traffic of the app). Hope to find time during the weekend.

**Comment by aNtiihEks** [comment]
Could be yes, if you need someone to test with you just let me know ;)

**Comment by mvdzwaan** [comment]
Issue in #33 is different. I do not get 403 messages. I posted more info in #33

**Comment by aNtiihEks** [comment]
Did u try to reload the intergration? After that I was not able to get connected no more.

**Comment by mvdzwaan** [comment]
It keeps working for me, after multiple HA restarts

**Comment by kranendijk** [comment]
Hi, same 403 issue here, restarts did not solve the issue unfortunately. Happy to help ehenever I can to test or alike.

Opnieuw proberen in te stellen: 403, message='Forbidden', url=URL('https://app-api.zonneplan.nl/connections/cd4310c4-9484-4aea-be54-fb9aed709fa7/summary')

**Comment by fsaris** [comment]
Got a response from Zonneplan and they confirmed that the api was adjusted.  Hope to provide a fix tomorrow evening.

Some responses are restructured.

**Comment by rdgout** [comment]
@fsaris to clarify, the summary endpoint is only available to people with an energy contract. This endpoint is never available unless you have a contract with product type `electricity` or `gas` in the `user-account/me` response for the connection.

**Comment by fsaris** [comment]
@rdgout Ah, tnx for the clarification. 
Will add a check for that

**Comment by fsaris** [comment]
Latest release https://github.com/fsaris/home-assistant-zonneplan-one/releases/tag/0.0.14 should revolve the error.

**Comment by kranendijk** [comment]
Back in business, great job!

**Comment by relighted** [comment]
Indeed. Updated and working instantly again. Many thanks.

**Comment by aNtiihEks** [comment]
Thanks a lot!
