### ISSUE TITLE
sensor.zonneplan_p1_electricity_production_compensation is unknown in the latest version

### ISSUE THREAD

**Issue by marcel-st** [fsaris/home-assistant-zonneplan-one#35]
Hi all,

i've upgraded to the latest version a couple of days ago and since that time the "sensor.zonneplan_p1_electricity_production_compensation" state is unknown.

Before, this sensor did work and specified the compensation i recieved by delivering energy back to the supplier.
I really liked this insight.

Is this a bug or did the feature end?

**Comment by fsaris** [comment]
Not sure where that sensor comes from, I do not recall that there was a `compensation` sensor. Did you create your own sensor bases on one of the sensors from the integration? Maybe based on the snippet that was part of the readme https://github.com/fsaris/home-assistant-zonneplan-one/commit/cf00e85337a830a72e3d6fb42b3c0d63a679815a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L72

This is now available as `Zonneplan P1 electricity returned today`

**Comment by marcel-st** [comment]
> Not sure where that sensor comes from, I do not recall that there was a `compensation` sensor. Did you create your own sensor bases on one of the sensors from the integration? 

nope, it was really there in a previous version, i don't (yet) know how to create this by myself.
Alhough i will start to look into it.

**Comment by fsaris** [comment]
Do you know what version (number) you used before?

**Comment by marcel-st** [comment]
> Do you know what version (number) you used before?

I belief it was 0.11, but it might have been 0.12.
I'm not 100% sure between the two because i can't find any logging of the update :-(

**Comment by fsaris** [comment]
checked the code again and the only sensor that was removed is `highest_measured_power` in the last x releases
