### ISSUE TITLE
Getting cheapest tariff and corresponding hour

### ISSUE THREAD

**Issue by rinseringma** [fsaris/home-assistant-zonneplan-one#38]
Hi!

Is there a way to get the cheapest tariff and get the corresponding hour with it? Just like shown in the Zonneplan app?

Would like to expose those values to Google Assistant so I could make a routine where I ask when the cheapest hour is and what the tariff is.

**Comment by tieskuh** [comment]
The forecast prices are in an attribute of the current_electricity_tariff sensor.
Try this in the template editor:

```
{% set cheapest = state_attr('sensor.zonneplan_current_electricity_tariff', 'forcast') 
                  | selectattr('datetime', '>', utcnow().isoformat())
                  | sort(attribute='price')  
                  | first %}

{{ cheapest.price /10000000 }}
{{ cheapest.datetime }}
```

<img width="679" alt="image" src="https://user-images.githubusercontent.com/115901851/211219241-27f8a565-6a39-459f-9b25-c12ad0859f58.png">



You can for example create a template sensor for the cheapest upcoming hour:

```
template:
  - sensor:
    - name: zonneplan_cheapest_hour
      state: >
        {% set cheapest = state_attr('sensor.zonneplan_current_electricity_tariff', 'forcast') 
                    | selectattr('datetime', '>', utcnow().isoformat())
                    | sort(attribute='price')  
                    | first %}
        {{ cheapest.datetime }}
```

Hope this helps.

**Comment by rinseringma** [comment]
Thanks! But somehow the date and price aren't the same as the Zonneplan app. But that has nothing to do with your script.

Two questions;
1. Is there a way to limit the quantity of forecast hours to the upcoming, let's say, 10 hours instead of 24 hours?
2. Is it possible to format the datetime stamp to only show the hour? And maybe calculate how many hours that is from the current time?

**Comment by tieskuh** [comment]
The price shown in the app is the lowest price of the current day (not taken in account the prices for the next day). I think that is why it's different.

You can do anything with the data you want.

For example, this will give you the next 10 hours:

```
{{ (state_attr('sensor.zonneplan_current_electricity_tariff', 'forcast') 
                  | selectattr('datetime', '>', utcnow().isoformat())
                  | sort(attribute='datetime'))
                  [:10] }}
```

Or the cheapest 10 hours:

```
{{ (state_attr('sensor.zonneplan_current_electricity_tariff', 'forcast') 
                  | selectattr('datetime', '>', utcnow().isoformat())
                  | sort(attribute='price'))
                  [:10] }}
```

And to only get the hour from the datetume you can use time functions: https://www.home-assistant.io/docs/configuration/templating/#time
For the example in my previous comment:

```
{% set cheapest = state_attr('sensor.zonneplan_current_electricity_tariff', 'forcast') 
                  | selectattr('datetime', '>', utcnow().isoformat())
                  | sort(attribute='price')  
                  | first %}

{{ cheapest.price /10000000 }}
{{ as_datetime(cheapest.datetime).hour }}
```

But I think these questions are not really in the right place. This is not an issue with this integration. I think you will find most answers to these questions in the community or feel free to send me a DM.

**Comment by tieskuh** [comment]
@fsaris Maybe you can enable discussions on your repository for these kind of questions

**Comment by fsaris** [comment]
Done https://github.com/fsaris/home-assistant-zonneplan-one/discussions
