### ISSUE TITLE
Is it possible to add Peak Power (Piekvermogen) value

### ISSUE THREAD

**Issue by dspooren** [fsaris/home-assistant-zonneplan-one#42]
Is it possible to get the values for the Peak Power (Piekvermogen) of the solarpanels. This value is visible in the app. I would like this as an entity in HomeAssistant.

![zonneplan](https://user-images.githubusercontent.com/18420047/211784345-638933d2-00fc-441f-9009-a4c49c0de8ed.png)

**Comment by fsaris** [comment]
Would suggest to use https://www.home-assistant.io/integrations/statistics/ for this.

I'm open for a PR to add this as extra sensor to the integration. But not sure if it's available as single value in the api response

**Comment by dspooren** [comment]
Thanks for your reply. Would be nice to add this as extra sensor, if it is available as a single value in the API.

**Comment by fsaris** [comment]
value doesn't seem to be available as a single value in the API. Suggest to use https://www.home-assistant.io/integrations/statistics/ if you want to have this value in HA
