### ISSUE TITLE
Forecast prices are not in euros

### ISSUE THREAD

**Issue by hmmbob** [fsaris/home-assistant-zonneplan-one#46]
The data in the forecast attributes contains prices that are not in euro (and need to be divided by 10000000 to get a reasonable euro price), while the state price of the sensor is in euros. This is unexpected behavior, it would be great if the prices in the attributes would be in euro's as well.

See screenshot:

![image](https://user-images.githubusercontent.com/33529490/213882817-05a805f6-9817-42dd-8ebb-89fccfcb9831.png)

**Comment by fsaris** [comment]
This is the raw api response and intentionally not converted
