### ISSUE TITLE
Zonneplan API unstable; cache results (longer)?

### ISSUE THREAD

**Issue by nl0pvm** [fsaris/home-assistant-zonneplan-one#49]
Hi,

I am assuming that i am not the only one having the issue below that the zonneplan API has become unstable, probably because of their succes. In economic terms this is called the winners curse. 

I hope that it is possible to cache the results as now all automations are all over the place because suddenly all kinds of sensors like the current tariff group are unavailable for short periods.

```
2023-02-04 15:24:38.910 ERROR (MainThread) [custom_components.zonneplan_one.coordinator] Error requesting zonneplan_one data: 503, message='Service Unavailable', url=URL('https://app-api.zonneplan.nl/connections/xxxxxxxx-xxx-xxxx-xxxx-xxxxxxxxxxxx/summary')
2023-02-04 16:01:31.294 ERROR (MainThread) [custom_components.zonneplan_one.coordinator] Error requesting zonneplan_one data: 503, message='Service Unavailable', url=URL('https://app-api.zonneplan.nl/connections/xxxxxxxx-xxx-xxxx-xxxx-xxxxxxxxxxxx/gas')
2023-02-04 16:07:44.764 ERROR (MainThread) [custom_components.zonneplan_one.coordinator] Error requesting zonneplan_one data: 503, message='Service Unavailable', url=URL('https://app-api.zonneplan.nl/user-accounts/me')
2023-02-04 16:28:03.373 ERROR (MainThread) [custom_components.zonneplan_one.coordinator] Error requesting zonneplan_one data: 503, message='Service Unavailable', url=URL('https://app-api.zonneplan.nl/connections/xxxxxxxx-xxx-xxxx-xxxx-xxxxxxxxxxxx/gas')
2023-02-04 18:38:08.960 ERROR (MainThread) [custom_components.zonneplan_one.coordinator] Error requesting zonneplan_one data: 503, message='Service Unavailable', url=URL('https://app-api.zonneplan.nl/connections/xxxxxxxx-xxx-xxxx-xxxx-xxxxxxxxxxxx/electricity-delivered')
2023-02-04 18:50:18.628 ERROR (MainThread) [custom_components.zonneplan_one.coordinator] Error requesting zonneplan_one data: 503, message='Service Unavailable', url=URL('https://app-api.zonneplan.nl/user-accounts/me')
2023-02-04 19:41:04.782 ERROR (MainThread) [custom_components.zonneplan_one.coordinator] Error requesting zonneplan_one data: 503, message='Service Unavailable', url=URL('https://app-api.zonneplan.nl/connections/xxxxxxxx-xxx-xxxx-xxxx-xxxxxxxxxxxx/electricity-delivered')
2023-02-04 20:40:15.874 ERROR (MainThread) [custom_components.zonneplan_one.coordinator] Error requesting zonneplan_one data: 503, message='Service Unavailable', url=URL('https://app-api.zonneplan.nl/connections/xxxxxxxx-xxx-xxxx-xxxx-xxxxxxxxxxxx/summary')
2023-02-04 21:04:51.432 ERROR (MainThread) [custom_components.zonneplan_one.coordinator] Error requesting zonneplan_one data: 503, message='Service Unavailable', url=URL('https://app-api.zonneplan.nl/connections/xxxxxxxx-xxx-xxxx-xxxx-xxxxxxxxxxxx/gas')

```

**Comment by fsaris** [comment]
Looks like a temporary hickup on there side

**Comment by JohanEikelenboom** [comment]
I have the same error, since last friday.

**Comment by mvzut** [comment]
I have the same, the service is unavailable very often, many times per hour. The own Zonneplan app seems to work fine during those moments. Can it be something else then their server having problems?

**Comment by mvzut** [comment]
I am also relying on this plugin for my energy use logging. But I'm afraid, when these problems continue, I can better use a P1 splitter and log energy usage directly from the P1 port again, like I did before...

**Comment by FreddyX078** [comment]
Same here, it is completely unusable at this moment. Goes down every 5-15 minutes.

**Comment by JohanEikelenboom** [comment]
It looks like the API is working again

**Comment by fsaris** [comment]
mmm, need to check the HA inner code again. My logs show that even when the api call fails it uses the previous values, but somehow the values are not visible in the stats.

**Comment by FreddyX078** [comment]
I think they fix it before they left the office because no more errors after 17.00 :-)

**Comment by Ascathon** [comment]
It seems their app wont work during these times either.

**Comment by sniperxnl** [comment]
Same issue here, app is working

**Comment by hbeekhuis** [comment]
Same here, all entities (except gas price for some reason) unavailable right now.
A couple of days ago it was the other way around, then the gas price was unavailable.

Where can I find logs, would that help?

**Comment by rdgout** [comment]
@fsaris we can see in the api that some installations are performing an update request _every_ minute. Our data only refreshes every 5 minutes. So this means that these installations are basically spamming our API with pointless requests.
It would be great if you could setup a refresh time of 5 minutes or more. This would reduce the, pointless, load on our api.

**Comment by hbeekhuis** [comment]
As I (and perhaps others?) am only using the hourly changing pricefeeds for my total cost and smart device integrations, perhaps in a future update the interval could be settable according to usage, during setup?
So 
- when using 'live' data like current power consumption, set 5 min interval
- When using hourly rates only: 30 minute interval (or so)

**Comment by deqw** [comment]
@hbeekhuis I'm using the price to trigger charging. Your solution results in waiting much too long before I can start and stop charging.

**Comment by hmmbob** [comment]
It probably needs a redesign of the solution. The price information (the source) actually changes only once a day (around 1-2pm currently) - all info is then "known" and can be used for the sensors later in the day (it won't change anymore - all prices for all timeframes are known already) including the "actual tariff" sensor. So that would negate the need to request all data every 5 mins.

**Comment by deqw** [comment]
@hmmbob That would work. And maybe doing regular requests when the time window that lays ahead shortens too much (eg. when no updates came in at the expected time).

**Comment by fsaris** [comment]
Another option would be respecting the etag caching headers. But didn't yet find a native python solution for this. Will give it some more thought. Help is welcome :)

**Comment by fsaris** [comment]
@deqw @hmmbob I added the ETag to the request header. Now Zonneplan can tell us if there is updated data. Every endpoint is polled every 10 seconds and depending on the ETag check (that they perform) we get new data or a status 304 Not Modified. This should give more up-to-date data for the charge points without hammering there API

**Comment by rdgout** [comment]
> @deqw @hmmbob I added the ETag to the request header. Now Zonneplan can tell us if there is updated data. Every endpoint is polled every 10 seconds and depending on the ETag check (that they perform) we get new data or a status 304 Not Modified. This should give more up-to-date data for the charge points without hammering there API

Hi @fsaris, 
This is not how ETags work,

**Comment by fsaris** [comment]
@rdgout okay, that's a unfortunate  😄 

Will revert it back. Can you tell me with what interval the `charge point` endpoint updates its values? Especially after performing an action as start/stop charge.

**Comment by rdgout** [comment]
> @rdgout okay, that's a unfortunate 😄
> 
> Will revert it back. Can you tell me with what interval the `charge point` endpoint updates its values? Especially after performing an action as start/stop charge.

Charge points update on a fixed 5 minute schedule, however, they may also send updates every time something changes.
What we do in the app is poll for updates _after_ we request a change for a fixed period until we see the change has happened. This will require some sort of keeping state to know when the change has happened otherwise it will be just asking for data continuously.  

So basically what you could do:
1. Send instruction (like boost, stop charging)
2. Poll every 10 seconds to see if the change has happened. (started or stopped charging with a maximum of a minute, so 6 times)
3. If the change has not happened after this minute, assume the instruction has failed.

It would be great however if you would not implement this in a naive way where the plugin just keeps trying to send instructions and spam our API anyway, instructions may fail for any number of reasons like: 
- The charge point is disconnected (literally turned off by the client)
- 4G is not working due to a network / ISP error
- The charge point is not connected to a car

If you could make sure instructions are sent only when the car is connected AND not in an error state, that would probably resolve most issues that could arise otherwise.

**Comment by fsaris** [comment]
@rdgout the refresh was only for a short time set to 10 seconds and this wasn't part of a official release. Maybe it are the charge point users that are testing a beta, but there was also already a new release that only polls every 5 minutes.

Will have a look at the summary call

**Comment by fsaris** [comment]
@rdgout the 0.021b1 release had a 10sec interval for the poll. Just removed that beta release. The new beta release was released yesterday so all users that use the beta will probably update soon and that should result in less traffic for your server's
