### ISSUE TITLE
[Question] High/Low tariff sensor values always zero

### ISSUE THREAD

**Issue by Broekman** [fsaris/home-assistant-zonneplan-one#5]
Hi Frans,

All still working perfectly, but had a question regarding the P1 tariff values.

At the moment, only normal tariff has a value, however high- and low tariff are always reported zero. Do you by any chance know if these are actually provided/filled in the Zonneplan interface or just there as a placeholder?

Thanks!

**Comment by fsaris** [comment]
Hi,

These should give you the same info as in de Zonneplan app on the `Stroom gekocht` overview.

At least for me these values seem to match :)

**Comment by Broekman** [comment]
Ah, I don't buy power from them so that could explain things (also don't have this in the app). Thanks!
