### ISSUE TITLE
No current tariff changes event

### ISSUE THREAD

**Issue by Paul1865** [fsaris/home-assistant-zonneplan-one#54]
I tried to build an automation on the current tariff (put plug on below x cents and turn off above x cents). 
But there is only current-low-tariff change, normal and high.
Possible to add the current one?😊
I know there is a sensor with the current tariff, but I cannot use that in an automation sadly.

**Comment by fsaris** [comment]
Not sure if I understand the issue.

You have the `Zonneplan current electricity tariff` but it doesn't trigger change events?

Are you sure you use the correct entity and state in the automation? Can you post a screenshot of the history of the sensor?

**Comment by Paul1865** [comment]
Leave it...
I used the Connect device instead of the usage :/ ....
![image](https://user-images.githubusercontent.com/17167055/219718531-dc9742c7-d1e9-4bd4-8bcc-a4dc49e95fd7.png)

instead of:

![image](https://user-images.githubusercontent.com/17167055/219718658-7901d0b4-c870-48fd-afaf-44c72603c91e.png)
