### ISSUE TITLE
Meter readings

### ISSUE THREAD

**Issue by nvanoost** [fsaris/home-assistant-zonneplan-one#56]
Hi,

Is it possible to get the meter readings from the P1 device? I would like to read them as well so I can upload them automatically to mindergas.nl with HA.

**Comment by fsaris** [comment]
These values are not provided by the api of Zonneplan

**Comment by hmmbob** [comment]
@nvanoost you might want to look at something like https://www.zuidwijk.com/product/slimmelezer-plus/ (and a P1 splitter to use this Slimme Lezer and the Connect at the same time)
