### ISSUE TITLE
Sometimes the current elek/gas tarif is nothing

### ISSUE THREAD

**Issue by Senshin86** [fsaris/home-assistant-zonneplan-one#59]
So sometimes the system forgets the prices, when it updates new hourly data for gas and elec it doesnt register a updated price.
Is there something possible between refreshing when it fails it can keep the old/current price in stead of forgetting the price for like 5 minutes becuase of the update.

hopefully you know what i mean.

Sjoerd

**Comment by jhjdekker98** [comment]
Seems like this could be solved pretty easily using a globally scoped variable in [coordinator::_fetch_data](https://github.com/fsaris/home-assistant-zonneplan-one/blob/e417cd240bbc5acab4cfb77dec3abf51d867a42b/custom_components/zonneplan_one/coordinator.py#L55) that holds the values for the `result`-object that gets returned by that function.

I'm not familiar at all with the codebase and I can't find any usage reference to the calling method `coordinator::_async_update_data` using GitHub's search function - so I'm not sure this possible solution would cause any other problems.

**Comment by fsaris** [comment]
Do you only have this for the price sensors? And multiple times a day or only at a specific time a day?

**Comment by kababoom** [comment]
I got this too, not found a pattern yet..

It's annoying since it messes up the estimated energy costs.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/16404944/226425796-8f690c3b-74b6-4704-a4dc-4e1ff608e020.png">

**Comment by DaWacko87** [comment]
I am having the same issue since 12 o'clock today for the current electricity price sensor only.

**Comment by Paul1865** [comment]
Thanks!! Just updated :)
