### ISSUE TITLE
Add Support for Long-term Statistics

### ISSUE THREAD

**Issue by pve84** [fsaris/home-assistant-zonneplan-one#6]
The new Home Assistant energy dashboard requires entities to have a state_class attribute set to measurement. Without the attribute it's not possible to select the Zonneplan sensors. See: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by fsaris** [comment]
Yes it's on my list. Hope to have something tomorrow :)

**Comment by Broekman** [comment]
Thanks!
