### ISSUE TITLE
Daylight saving time 

### ISSUE THREAD

**Issue by ronaldt80** [fsaris/home-assistant-zonneplan-one#60]
My sensor shows a different value for electricity price vs the zonneplan app. It seems to be one hour too soon (eg it now shows the value for next hour) - anyone else experience the same? It may have to do with the array which has one value less (eg no value for 2am) this would explain why this integration appears 1 hour ahead.

**Comment by hmmbob** [comment]
Correcte aanname, de ruwe data heeft wel de juiste gegevens:

Het is nu 20:15 NL zomertijd, wat Z+02:00 is, dus in Z is het nu 18:15. De data hieronder heeft aan dat de prijs van 2916819 is, wat klopt met de app (29 ct). Over een uur (vanaf 19:00Z, dus 21:00 NL) geeft de ruwe data hieronder 2820503 aan, wat overeenkomt met de waarde in de app.

```
- price: 2916819
  electricity_price: 2916819
  tariff_group: normal
  solar_percentage: 0
  solar_yield: 0
  datetime: '2023-03-26T18:00:00.000000Z'
  sustainability_score: 331
  carbon_footprint_in_grams: 2331
- price: 2820503
  electricity_price: 2820503
  tariff_group: normal
  solar_percentage: 0
  solar_yield: 0
  datetime: '2023-03-26T19:00:00.000000Z'
  sustainability_score: 274
  carbon_footprint_in_grams: 2192
```

**Comment by hmmbob** [comment]
Vermoedelijk omdat hier altijd het 25ste element wordt gekozen (telling begint met 0):

https://github.com/fsaris/home-assistant-zonneplan-one/blob/e417cd240bbc5acab4cfb77dec3abf51d867a42b/custom_components/zonneplan_one/const.py#L84-L98

Oplossing zou zijn om alle datetime's te parsen en daaruit de juiste te selecteren.

**Comment by ronaldt80** [comment]
Denk het niet inderdaad, we zien het morgen vanzelf - dan pas weer een probleem bij ingaan wintertijd wanneer er een waarde teveel zal zijn. Dus 7 maanden om het op te lossen!

**Comment by luchtgitaar** [comment]
Werkt het nu (dankzij zomertijd) zoals het zou moeten werken? En heeft het blijkbaar al die maanden niet met de juiste bedragen gewerkt?

**Comment by hmmbob** [comment]
> Werkt het nu (dankzij zomertijd) zoals het zou moeten werken? 

Ja

> En heeft het blijkbaar al die maanden niet met de juiste bedragen gewerkt?

Nee.

Rondom de zomertijd zat er een uur minder in de data, waardoor de waardes verkeerd liepen. Na 24u zat weer de normale hoeveelheid uren in de data. Zal ongetwijfeld in de herfst nog een keer gebeuren.

**Comment by fsaris** [comment]
No issues reported when switching to Daylight saving time so closing this ticket
