### ISSUE TITLE
charge_point (laadpaal) stopped working

### ISSUE THREAD

**Issue by holobeer** [fsaris/home-assistant-zonneplan-one#61]
It appears the charge_point data is no longer available since yesterday (april 10th)
I tried restarting HA and reinstalling the plugin (0.0.17), but to no effect.
In Home Assistant all Charge point sensors have the state Unavailable
![image](https://user-images.githubusercontent.com/100840996/231259138-7bdc3fde-0b3f-4217-aee2-d1c843fe08ef.png)

The other Zonneplan devices and sensors ( Usage, PV installatie and Connect energiemeter) work as intented.

I enabled debug logging and the following message appears while loading:

> 2023-04-11 19:47:15.397 INFO (MainThread) [custom_components.zonneplan_one.coordinator] Could not find charge_point of charge_point

I attached the captured (and redacted) log entries.
- logfile removed -

**Comment by holobeer** [comment]
After checking the logfiles i discoverd the API has been changed. The connection "charge_point" has been renamed by Zonneplan to "charge_point_installation".
I went through the code and made the changes to const.py, coordinator.py and sensor.py. After changing the names the charge point data is working again.

**Comment by hmmbob** [comment]
So you will create a pull request here?

**Comment by holobeer** [comment]
> So you will create a pull request here?

Yes, just fin
