### ISSUE TITLE
Current electricity tariff 'unknown'

### ISSUE THREAD

**Issue by nl0pvm** [fsaris/home-assistant-zonneplan-one#65]
Yep once again zonneplan changed their API that breaks this plugin. This time they changed the current electricity tariff. 

In the attributes of the current_electricity_tariff sensor the name of the electricity price is changed from **'price'** to **'electricity_price'**. My (could be wrong) assumption is that this also breaks the plugin.

**Comment by fsaris** [comment]
See https://github.com/fsaris/home-assistant-zonneplan-one/issues/63
