### ISSUE TITLE
Gas en electra prijzen standaard paar cent hoger dan in de zonneplan app

### ISSUE THREAD

**Issue by michelnumans** [fsaris/home-assistant-zonneplan-one#69]
Gas en electra prijzen standaard paar cent te hoog. Hoe kan ik dit aanpassen?

**Comment by jperquin** [comment]
+1.

Trek uurtarieven binnen via deze integratie en ook via enever.nl.

De data die van enever komt sluit wel bij die van de ZP app, en van deze integratie is idd hoger, maar dat varieert ook weer. Raar..

**Comment by hmmbob** [comment]
Grappig, want ik zit zojuist alle prijzen van vandaag te vergelijken en het klopt gewoon tot op de honderdste nauwkeurig.

Ook bijzonder, want HA haalt die prijsinformatie uit exact dezelfde bron als de app (met jouw eigen inloggegevens).... Ergens gaat er dus iets mis.

Er is een "known issue" dat de _vorige_ prijs aan het begin van het uur wat langer blijft hangen. Oftwel, het kan zijn dat je om 11:02 nog de prijs van 10:00-11:00 ziet, totdat er weer een update cycle is geweest. Is dit misschien wat jullie bedoelen?

**Comment by michelnumans** [comment]
Zie bovenstaande foto's. Aantal voorbeelden van de prijs van morgen van 12.00 uur, 13.00 uur en 14.00 uur. Ter aanvulling, zie ook de gasprijs,  deze is ook in home assistant structureel hoger dan in de zonneplan app

**Comment by hmmbob** [comment]
Hoe ziet je `data_generator` eruit?

Ik heb overigens exact dezelfde prijzen in de app, en in die HA zijn ook hetzelfde als mijn app

**Comment by michelnumans** [comment]
![Screenshot_20230609_213311_Home Assistant](https://github.com/fsaris/home-assistant-zonneplan-one/assets/123810901/993b7ff2-a576-48a8-b187-ffeef2b69bf4)
![Screenshot_20230609_213427_Home Assistant](https://github.com/fsaris/home-assistant-zonneplan-one/assets/123810901/5d590242-6bce-471e-8c32-5eaae8a0876f)
![Screenshot_20230609_213824_Home Assistant](https://github.com/fsaris/home-assistant-zonneplan-one/assets/123810901/f3cf5eb7-7181-40d9-a6e3-08432bfb7af0)
![Screenshot_20230609_213400_Zonneplan](https://github.com/fsaris/home-assistant-zonneplan-one/assets/123810901/1657f58b-24a9-436b-9f76-822f27f89171)
![Screenshot_20230609_213412_Zonneplan](https://github.com/fsaris/home-assistant-zonneplan-one/assets/123810901/3d71a184-3930-4fda-94c1-37da1e7cbad8)
![Screenshot_20230609_213451_Zonneplan](https://github.com/fsaris/home-assistant-zonneplan-one/assets/123810901/cc6285ab-9a9e-4ee1-86a2-0e7a6c8abe15)

**Comment by michelnumans** [comment]
> Hoe ziet je `data_generator`eruit?
> 
> Ik heb exact dezelfde prijzen in de app ingevoerd, en in die HA zijn ook dezelfde als mijn app

data_generator: |
      return entity.attributes.forecast.map((entry) => {
         return [new Date(entry.datetime), entry.electricity_price / 10000000];
       });

**Comment by Servizio-R** [comment]
I have the same problem since a few days (basically since updating to 0.0.19)
Prior to this the prices used to exactly the same...

**Comment by jperquin** [comment]
Lijkt er dus op dat het een bug is van de integratie. Zou mooi zijn als iemand er naar kan kijken..

**Comment by michelnumans** [comment]
Vandaag heb ik de integratie verwijderd en opnieuw in de nieuwste versie van home assistant geïnstalleerd. 

Het gekke is dat in de grafiek de waardes nu wel kloppen maar in een andere card die alleen de waardes van stroom en gas laten zien (zonder grafiek) staat het voor stroom 2 cent te hoog en gas 3 cent ( zie foto)
![20230622_215451](https://github.com/fsaris/home-assistant-zonneplan-one/assets/123810901/9f6b5f90-0f5b-41ea-a6ac-838641c55d29)

**Comment by MichNLGithub** [comment]
> ![Screenshot_20230609_213311_Home Assistant](https://user-images.githubusercontent.com/123810901/244787638-993b7ff2-a576-48a8-b187-ffeef2b69bf4.jpg) ![Screenshot_20230609_213427_Home Assistant](https://user-images.githubusercontent.com/123810901/244787657-5d590242-6bce-471e-8c32-5eaae8a0876f.jpg) ![Screenshot_20230609_213824_Home Assistant](https://user-images.githubusercontent.com/123810901/244787668-f3cf5eb7-7181-40d9-a6e3-08432bfb7af0.jpg) ![Screenshot_20230609_213400_Zonneplan](https://user-images.githubusercontent.com/123810901/244787677-1657f58b-24a9-436b-9f76-822f27f89171.jpg) ![Screenshot_20230609_213412_Zonneplan](https://user-images.githubusercontent.com/123810901/244787687-3d71a184-3930-4fda-94c1-37da1e7cbad8.jpg) ![Screenshot_20230609_213451_Zonneplan](https://user-images.githubusercontent.com/123810901/244787695-cc6285ab-9a9e-4ee1-86a2-0e7a6c8abe15.jpg)

Hoe krijgt u deze mooie grafiek in HA?

**Comment by fsaris** [comment]
probably some rounding error in the card you use. 

Closing this as I understood from the comments that the sensor values are correct
