### ISSUE TITLE
New property: Tomorrows gas price

### ISSUE THREAD

**Issue by renslinden** [fsaris/home-assistant-zonneplan-one#73]
Since the last Zonneplan App update they are publishing the new gas price already the day before around 18.30 PM.
It would be nice if we have this price as a new sensor within this integration.

Release notes Jun 29, 2023 (https://play.google.com/store/apps/details?id=com.zonneplanapp):
```
Met deze update publiceren we de gasprijs van de volgende dag veel sneller. Ongeveer rond 18:30 uur verschijnt de prijs in het dashboard. Zo kun je als klant je gasverbruik eerder sturen naar een ander moment. Daarnaast is de app op enkele punten verbeterd.
```

**Comment by fsaris** [comment]
I don't have a energy contract so will not get these values.

Can you post the debug info maybe we can spot the value and add it as sensor to the integration. https://github.com/fsaris/home-assistant-zonneplan-one#troubleshooting

**Comment by fsaris** [comment]
@renslinden could you test current main (beta) version?

**Comment by renslinden** [comment]
Looks good so far, unfortunately there is no price change over the weekend so it shows me the current price.

It might be better to show None or Unknown instead.

![Screenshot_2023-11-18-13-19-55-50_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/fsaris/home-assistant-zonneplan-one/assets/8656122/96b3cc2c-de31-4804-be09-ac98753b4be6)

**Comment by fsaris** [comment]
It's the next known value. 
Can you add the debug output here? Or check it for the `gas_price` value? I expect that tomorrow is filled with this value even if it doesn't change regarding to today.

**Comment by renslinden** [comment]
Yes i know, I've checked your change. You revert the list and pick the first item as the next day price, right?

Currently there is only one price available from the ZP api:

```
{'electricity_price': 2767377, 'gas_price': 12002777, 'tariff_group': 'low', 'solar_percentage': 0, 'solar_yield': 0, 'datetime': '2023-11-18T05:00:00.000000Z', 'sustainability_score': 176}
```

**Comment by fsaris** [comment]
are you sure the price isn't updated during the weekend? Maybe it's only know every day after 18:30 like you mentioned in your first message.

**Comment by renslinden** [comment]
As far as I know during the weekend the gas market is closed so the current price is valid till Monday 6.00 AM.

Anyways, does it impact the implementation? I don't think so.

Is there anything I can test/debug/clarify for you?

**Comment by renslinden** [comment]
So let me elaborate a bit more. This is what I see at this moment in the Zonneplan app.

![IMG_20231118_145957.jpg](https://github.com/fsaris/home-assistant-zonneplan-one/assets/8656122/3a0dc434-4e56-4158-ae0b-eb73d18b88bf)

Around the clock of 6/7 PM the tomorrow's price will become available and is shown underneath 'Gasprijs vandaag'. Unfortunately I currently do not have a screenshot of that.

Technical wise the API gives two gas prices.

In the morning the tomorrow's price disappear from the app. As the next price is not known anymore. At this moment I do expect a sensor with status None or Unknown.

Technical wise the API gives only one gas price.

**Comment by fsaris** [comment]
@renslinden updated the code to only show a `next` gas price when there is a next price known (there a 2 prices in the list)

**Comment by renslinden** [comment]
Getting an error with latest version:

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.zonneplan_one.coordinator
Source: helpers/update_coordinator.py:290
Integration: Zonneplan ONE (documentation, issues)
First occurred: 16:38:14 (4 occurrences)
Last logged: 16:40:32

Unexpected error fetching zonneplan_one data: name 'false' is not defined
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zonneplan_one/coordinator.py", line 63, in _async_update_data
    return await self._fetch_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zonneplan_one/coordinator.py", line 120, in _fetch_data
    result[uuid]["summary_data"]["gas_price_next"] = getNextGasPriceFromSummary(summary)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zonneplan_one/coordinator.py", line 32, in getNextGasPriceFromSummary
    first_price_found = false
                        ^^^^^
NameError: name 'false' is not defined
```

**Comment by fsaris** [comment]
@renslinden wrong value is fixed

**Comment by renslinden** [comment]
It looks good so far!

This was the situation before 6 AM:

![Screenshot_2023-11-18-18-13-18-07_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/fsaris/home-assistant-zonneplan-one/assets/8656122/6e0589e6-d0b7-4b3c-88aa-83d8afa30099)

And this after 6 PM:

![IMG_20231119_004047.jpg](https://github.com/fsaris/home-assistant-zonneplan-one/assets/8656122/ca66a5a0-d680-404d-ae08-ad62ebdac9d8)

![Screenshot_2023-11-19-00-41-26-06_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/fsaris/home-assistant-zonneplan-one/assets/8656122/16112fc0-7d3f-405f-9752-1368d5f3575b)

**Comment by renslinden** [comment]
The situation this morning:

![Screenshot_2023-11-19-08-27-55-62_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/fsaris/home-assistant-zonneplan-one/assets/8656122/3aa62e5b-c5ee-4b4c-99ab-1596863e6efc)

So what I notice is that the state didn't reset to Onbekend / Unknown. That's what I initially did expect, but we can ask ourselves if that should be the desired option.

What do you think?

**Comment by fsaris** [comment]
Can you check the data you receive from the api? It should go back to unknown if there aren't 2 prices in the data

**Comment by fsaris** [comment]
Ah, there was still some use of known value in place

**Comment by renslinden** [comment]
I'll let you know if it works as expected. Thanks!

**Comment by renslinden** [comment]
Can confirm that it works as expected, good job!

Ready to release

**Comment by fsaris** [comment]
released https://github.com/fsaris/home-assistant-zonneplan-one/discussions/86
