### ISSUE TITLE
Add integration version to API call headers 

### ISSUE THREAD

**Issue by fsaris** [fsaris/home-assistant-zonneplan-one#88]
> Op dit moment is het voor ons niet te zien welke versie van de plugin nu gebruikt wordt, zou mooi zijn als deze toegevoegd kunnen worden aan de headers @fsaris

_Originally posted by @dstollie in https://github.com/fsaris/home-assistant-zonneplan-one/issues/87#issuecomment-1838446180_

**Comment by fsaris** [comment]
@dstollie @developmentzonneplan preferences how to name+format this header?

**Comment by fsaris** [comment]
Next version will add a `x-ha-integration` header to each request

**Comment by dacootmeister** [comment]
installing 0.0.22b1, lets wait and see

**Comment by fsaris** [comment]
missed to add the header to most of the request :) 

New version tagged 0.0.22b2
