### ISSUE TITLE
Zonneplan last measured value update only once per hour

### ISSUE THREAD

**Issue by willemstoker** [fsaris/home-assistant-zonneplan-one#97]
Hi,

I noticed that "Zonneplan last measured value" (which shows the current power that is produced in W) only updates once per hour. This used to be every 5 min. Why is that changed? Is it possible to update this every 5 minutes again?

The total yield is still updated every 5 minutes, so the API is called anyway?

**Comment by fsaris** [comment]
See https://github.com/fsaris/home-assistant-zonneplan-one/pull/91#issuecomment-1884853304

**Comment by willemstoker** [comment]
Thanks! Is there anything I can do in the meanwhile?

**Comment by fsaris** [comment]
Maybe use yield today. That is updated more often and with more precision.

see #94

**Comment by willemstoker** [comment]
The latest release fixed this, thanks!!

It's nice to see the difference in the detail on the graph comparing yesterday and today :D
![image](https://github.com/fsaris/home-assistant-zonneplan-one/assets/8770969/8e7b02dd-9a4b-4fb0-965b-27a0d2cbdb92)
